# Generated by Django 5.2.3 on 2025-06-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Categorias',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
