# Generated by Django 5.2.3 on 2025-06-18 20:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto do post'),
        ),
    ]
